# Generated by Django 3.0.5 on 2020-04-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_college', models.CharField(max_length=100)),
                ('Area_name', models.CharField(max_length=100)),
            ],
        ),
    ]
