# Generated by Django 3.0.5 on 2020-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='Area_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='areas',
            name='Area_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='areas',
            name='Area_image',
            field=models.ImageField(default='', upload_to='areas/images'),
        ),
        migrations.AddField(
            model_name='areas',
            name='Area_price',
            field=models.IntegerField(default=0),
        ),
    ]
